# States that the lexer can be in
# Which states can it transition into
# Which token kinds need to be lexed in order to do so
STATE_DEFINITIONS = {
    "BLOCK": {
        "BLOCK": ["MULTI_NEWLINE"],
        "HEADING_BLOCK": ["BANG"],
        "CODE_BLOCK": ["TRIPLE_BACKTICK"],
        "UNORDERED_LIST_BLOCK": ["HYPHEN"],
        "ORDERED_LIST_BLOCK": ["PLUS"],
        "PARAGRAPH_INLINE_CODE": ["BACKTICK"],
        "PARAGRAPH_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    
    # Paragraph
    "PARAGRAPH_INLINE": {
        "BLOCK": ["MULTI_NEWLINE"],
        "PARAGRAPH_INLINE_CODE": ["BACKTICK"],
        "PARAGRAPH_INLINE": ["NEWLINE", "ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "MULTI_NEWLINE"]
    },
    "PARAGRAPH_INLINE_CODE": {
        "PARAGRAPH_INLINE": ["BACKTICK"],
        "PARAGRAPH_INLINE_CODE": ["NEWLINE", "TEXT", "BACKTICK"]
    },
    
    # Heading
    "HEADING_BLOCK": {
        "HEADING_BLOCK": ["BANG"],
        "HEADING_INLINE_CODE": ["BACKTICK"],
        "HEADING_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    "HEADING_INLINE": {
        "BLOCK": ["MULTI_NEWLINE"],
        "HEADING_INLINE_CODE": ["BACKTICK"],
        "HEADING_INLINE": ["NEWLINE", "ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "MULTI_NEWLINE"]
    },
    "HEADING_INLINE_CODE": {
        "HEADING_INLINE": ["BACKTICK"],
        "HEADING_INLINE_CODE": ["NEWLINE", "TEXT", "BACKTICK"]
    },
    
    # Code block
    "CODE_BLOCK": {
        "BLOCK": ["TRIPLE_BACKTICK"],
        "CODE_BLOCK": ["TEXT", "TRIPLE_BACKTICK"]
    },
    
    # Unordered list
    "UNORDERED_LIST_BLOCK": {
        "UNORDERED_LIST_INLINE_CODE": ["BACKTICK"],
        "UNORDERED_LIST_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    "UNORDERED_LIST_INLINE": {
        "BLOCK": ["MULTI_NEWLINE"],
        "UNORDERED_LIST_MARKER": ["NEWLINE"],
        "UNORDERED_LIST_INLINE_CODE": ["BACKTICK"],
        "UNORDERED_LIST_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    "UNORDERED_LIST_MARKER": {
        "UNORDERED_LIST_BLOCK": ["HYPHEN"]
    },
    "UNORDERED_LIST_INLINE_CODE": {
        "UNORDERED_LIST_INLINE": ["BACKTICK"],
        "UNORDERED_LIST_INLINE_CODE": ["TEXT", "BACKTICK"]
    },
    
    # Ordered list
    "ORDERED_LIST_BLOCK": {
        "ORDERED_LIST_INLINE_CODE": ["BACKTICK"],
        "ORDERED_LIST_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    "ORDERED_LIST_INLINE": {
        "BLOCK": ["MULTI_NEWLINE"],
        "ORDERED_LIST_MARKER": ["NEWLINE"],
        "ORDERED_LIST_INLINE_CODE": ["BACKTICK"],
        "ORDERED_LIST_INLINE": ["ASTERISK", "SLASH", "UNDERSCORE", "TILDE", "TEXT", "BACKTICK", "NEWLINE", "MULTI_NEWLINE"]
    },
    "ORDERED_LIST_MARKER": {
        "ORDERED_LIST_BLOCK": ["PLUS"]
    },
    "ORDERED_LIST_INLINE_CODE": {
        "ORDERED_LIST_INLINE": ["BACKTICK"],
        "ORDERED_LIST_INLINE_CODE": ["TEXT", "BACKTICK"]
    }
}

DEFAULT_STATE = "BLOCK"